#!/bin/bash
source /home/cheyulin/Community-Detection/shellscripts/removeTempFiles.sh
function runMcl(){
    for file in ` ls $1 `
    do
        if [ -d $1"/"$file ]
        then
            runMcl $1"/"$file
        else
            
            if [[ $file =~ .*edges_input.csv$ ]];then
                echo $file
                #run Mcl
                declare -i tempint=12
                while((tempint<51))
                do 
                    echo $tempint
                    inflation=$(echo $tempint|awk '{printf "%.2f\n",$1/10.00}')
                    echo $inflation
                    execMcl $1 $file $inflation 
                    let tempint+=1
                done
            fi
        fi
    done
    removeTmpFiles $1
}

function execMcl(){
    file=$2
    init_infile=$1"/"$file
    temp_clu_file=${init_infile//input.csv/temp_output_mcl_$3.csv}
    startTime=$(date +%s.%Nns)
    mcl $init_infile --abc -I $3 -o $temp_clu_file
    endTime=$(date +%s.%Nns)

    #output processing
    java_path="/home/cheyulin/Community-Detection/java_project/bin"
    java_infomap_op_class="op.MclOP"
    cd $java_path
    clu_out_file=${init_infile//edges_input.csv/mcl_$3.clu}
    java  $java_infomap_op_class $temp_clu_file $clu_out_file

    #measurement
    truthfile=${file//edges_input.csv/ground_truth.csv}
    truth_file_num=$(find $1 -name $truthfile | wc -l)
    echo $truth_file_num
    if [[ $truth_file_num == "1" ]];then
        if [[ $truthfile =~ .*amazon.* ]];then
            echo "amazon"
            measurement_out_file=${init_infile//edges_input.csv/measurement_mcl_$3.us}
            attractor -E US $clu_out_file $init_infile $measurement_out_file
        else
            ground_truth_file=$1"/"$truthfile
            measurement_out_file=${init_infile//edges_input.csv/measurement_mcl_$3.s}
            attractor -E S  $clu_out_file $ground_truth_file $measurement_out_file
        fi
    else
        echo "hello"
        measurement_out_file=${init_infile//edges_input.csv/measurement_mcl_$3.us}
        echo $clu_out_file" "$init_infile" "$measurement_out_file
        attractor -E US $clu_out_file $init_infile $measurement_out_file
    fi

    echo "startTime:"$startTime >> $measurement_out_file
    echo "endTime:"$endTime >> $measurement_out_file
}

INIT_PATH="/home/cheyulin/Community-Detection/dataset/synthetic/test_case_5"
runMcl $INIT_PATH